# Generated by Django 4.0.6 on 2022-08-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_alter_issue_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='assignee_user_id',
            new_name='assignee_user',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='author_user_id',
            new_name='author_user',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='project_id',
            new_name='project',
        ),
    ]
