# Generated by Django 4.0.6 on 2022-08-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_issue_priority_alter_issue_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
