# Generated by Django 4.0.6 on 2022-07-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_title'),
        ('users', '0003_contributor_permission_alter_contributor_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together={('user_id', 'project_id')},
        ),
    ]
