# Generated by Django 4.0.6 on 2022-08-02 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_project_id_contributor_project_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contributor',
        ),
    ]
